typography_spectrum: 0.4587169172993797
color:
  brandColors:
    - '#C8CBB6'
    - '#9EA18D'
    - '#646964'
    - '#424445'
    - '#E8EBDF'
  brandStrength: 0.7617635739445318
  lightness: 0.6313617228735054
  saturation: 0.7968261766769361
  rhythmicContrast: 0.7878853604010316
github: true
layout_spectrum: 0.6890500054613568
author:
  name: Steve Dowell
  email: stephen.dowell@comcast.net
  url: 'http://stephendowell.net'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9884760-0f4c-4793-b738-16c40b3ca56d.png
name: Cognitive Design
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Home
    id: 0a97edf1-e220-442a-9a39-3573d2b9db65
    type: content
  - name: About
    id: 966b8681-837a-449a-869b-ff9038fa17d9
    type: content
  - name: Contact
    id: 9ca67cd3-d805-4685-b61b-b2b646417dbd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/618e8706-614c-493b-b8f5-d15decbb4413.png
title: Cognitive Design
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0695fc3f-f5e1-45c9-9c4a-2529cb25f970.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0695fc3f-f5e1-45c9-9c4a-2529cb25f970.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Sophistication through Simplicity
purpose:
  - type: external
    url: 'http://stephendowell.net/developer-services'
    label: Services
  - type: external
    url: 'https://live.vcita.com/site/steve.dowell'
    label: Book Now
analytics:
  google: UA-27033558-25
