color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.9192018781322986
  lightness: 0.18796529085375369
  saturation: 0.13136777468025684
  rhythmicContrast: 0.5250735294539481
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Cognitive Design
layout_spectrum: 0.31042208429425955
typography_spectrum: 0.7347155853640288
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/61756123-f3cd-4ca5-9a0a-f7ff3c8f1be1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/61756123-f3cd-4ca5-9a0a-f7ff3c8f1be1.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5a8f9aa-1003-4943-8918-2e25a785de7b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5a8f9aa-1003-4943-8918-2e25a785de7b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9c9e630-f36a-45aa-9a41-e0ff5f3c386c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9c9e630-f36a-45aa-9a41-e0ff5f3c386c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Cognitive Design
description: Sophistication through Simplicity
purpose:
  - type: external
    url: 'http://stephendowell.net/developer-services'
    label: Services
  - type: external
    url: 'https://live.vcita.com/site/steve.dowell'
    label: Book Now
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99ebd2e8-ba64-4a88-97ad-ec156d72806d.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f11bbcb-88e6-4fc0-b5ea-f1bdfc27786e.png
author:
  name: Steve Dowell
  email: stephen.dowell@comcast.net
  url: 'http://stephendowell.net'
