layout_spectrum: 0.6890500054613568
typography_spectrum: 0.4587169172993797
color:
  brandColors:
    - '#C8CBB6'
    - '#9EA18D'
    - '#646964'
    - '#424445'
    - '#E8EBDF'
  brandStrength: 0.7617635739445318
  lightness: 0.6313617228735054
  saturation: 0.7968261766769361
  rhythmicContrast: 0.7878853604010316
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Cognitive Design
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0695fc3f-f5e1-45c9-9c4a-2529cb25f970.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0695fc3f-f5e1-45c9-9c4a-2529cb25f970.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Cognitive Design
description: Sophistication through Simplicity
purpose:
  - type: external
    url: 'http://stephendowell.net/developer-services'
    label: Services
  - type: external
    url: 'https://live.vcita.com/site/steve.dowell'
    label: Book Now
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99ebd2e8-ba64-4a88-97ad-ec156d72806d.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f11bbcb-88e6-4fc0-b5ea-f1bdfc27786e.png
author:
  name: Steve Dowell
  email: stephen.dowell@comcast.net
  url: 'http://stephendowell.net'
